### ISSUE TITLE
转 pdf 时报错

### ISSUE THREAD

**Issue by keep-l** [asdw741111/jspdf-pro#13]
仅在element高度过高时出现，element转为 pdf 大概24页
执行render(true)时报错，Error: Invalid argument passed to jsPDF.scale

![image](https://github.com/user-attachments/assets/4e75488a-b457-449f-ae27-5b56feb5c803)

![截图_选择区域_20240812155947](https://github.com/user-attachments/assets/d90acc65-e4fa-42bd-b5f8-601ae8dd45f8)

**Comment by asdw741111** [comment]
看起来是jsPDF计算缩放的时候出现，由于宽度或者高度数值不正确导致。针对超长元素会自动提取下一级子元素来分别渲染，正常情况下是没问题的，你这个看起来和样式有关系。可以提供下element的html我看下哪里导致的。

**Comment by keep-l** [comment]
就是简单的表格，表格行数非常大，
![image](https://github.com/user-attachments/assets/1c557355-081d-48e6-b198-e3fe3af62102)

表格样式如下：
![image](https://github.com/user-attachments/assets/9d090d08-1394-41a5-a19f-45f4b816f59a)


> 看起来是jsPDF计算缩放的时候出现，由于宽度或者高度数值不正确导致。针对超长元素会自动提取下一级子元素来分别渲染，正常情况下是没问题的，你这个看起来和样式有关系。可以提供下element的html我看下哪里导致的。

**Comment by keep-l** [comment]
> 看起来是jsPDF计算缩放的时候出现，由于宽度或者高度数值不正确导致。针对超长元素会自动提取下一级子元素来分别渲染，正常情况下是没问题的，你这个看起来和样式有关系。可以提供下element的html我看下哪里导致的。

看了源码还是没找到问题出在哪

**Comment by asdw741111** [comment]
@keep-l 
![image](https://github.com/user-attachments/assets/23552b5b-fd15-45be-bd96-187182109a9b)
有元素高度是0导致的，可能是样式问题
