### ISSUE TITLE
表格的行被分割

### ISSUE THREAD

**Issue by keep-l** [asdw741111/jspdf-pro#14]
表格的行被分割到两个页中显示，如何才能在他溢出的时候，整行分配到下一页显示

![image](https://github.com/user-attachments/assets/f3145894-fb74-4001-b4c3-39bf16abb639)

**Comment by asdw741111** [comment]
参考readme，通过给行设置样式来控制：
.setClassControlFilter("isLeafWithoutDeepFilter", (v) => ["el-table__row", "ant-table-row"].includes(v)) // 针对element-ui和antd库的表格行样式做跨页处理
如果用的不是elementui或者antd，自行设置跨页元素的class
