### ISSUE TITLE
黑色主题下渲染问题

### ISSUE THREAD

**Issue by fanxiaoning-fe** [asdw741111/jspdf-pro#16]
大佬，我尝试将渲染的页面改为黑色主题为底色后，渲染的页面样式出现错乱和渲染不上，求解

**Comment by asdw741111** [comment]
@fanxiaoning-fe 得看下页面结构，黑色主题应该是导出pdf的元素父节点渲染的，会导致获取不到样式问题，因为现在是直接根据一个元素渲染canvas，脱离了页面，父元素样式不生效。错乱应该也是因为这个

**Comment by fanxiaoning-fe** [comment]
我尝试将渲染的根节点底色设置为黑色，但是渲染后的页面底色还是白色，我看是不是得htmlcanvas 的属性有个背景色设置给暴漏出来方便我们自己设置背景色呢

**Comment by asdw741111** [comment]
可以，下个版本会加背景色参数

**Comment by asdw741111** [comment]
@fanxiaoning-fe 0.1.8版本已经支持设置背景色

**Comment by fanxiaoning-fe** [comment]
@asdw741111  大佬666
