### ISSUE TITLE
table表格跨页，导致某行显示不完整

### ISSUE THREAD

**Issue by liuyuanyuannumberone** [asdw741111/jspdf-pro#17]
![sni](https://github.com/user-attachments/assets/00a49b7c-2c76-42e4-a9b2-ed582b2284e9)

**Comment by liuyuanyuannumberone** [comment]
@asdw741111  大佬请问以下这种情况怎么处理了

**Comment by liuyuanyuannumberone** [comment]
createPDF(document.getElementById("templateId")).margin({ left: 28.35, top: 28.35, bottom: 28.35, right: 28.35 }) .toPdf("文件名")，
我是这么做的

**Comment by asdw741111** [comment]
@liuyuanyuannumberone 你需要指定跨页的样式，参考readme，例如：
```js
createPDF(document.getElementById("templateId")).margin({ left: 28.35, top: 28.35, bottom: 28.35, right: 28.35 })
.setClassControlFilter("isLeafWithoutDeepFilter", (v) => ["el-table__row", "ant-table-row"].includes(v))
 .toPdf("文件名")
```

**Comment by liuyuanyuannumberone** [comment]
感谢大佬的回复，createPDF(document.getElementById("templateId"))
    .margin({ left: 28.35, top: 28.35, bottom: 28.35, right: 28.35 })
    .setClassControlFilter("isLeafWithoutDeepFilter", className => {
      if (["arco-table-tr"].includes(className)) {
        return true
      }
      return false
    }) 我试了，然后发现不同电脑打印出来的table ,有的是对的（正常），有的不正常，不知道这和什么有关系

**Comment by liuyuanyuannumberone** [comment]
现在正在排查，
![image](https://github.com/user-attachments/assets/b52c086f-d6c6-4efc-83ec-1a7fc396ce0f)
![image](https://github.com/user-attachments/assets/465e3693-12b7-4ddc-9c58-2c77c0f6be62)
da'yin打印出来的canvas 不同电脑大小还是不一样

**Comment by liuyuanyuannumberone** [comment]
大佬你写的应该是网上写的很好的了，希望能继续维护，看了你的源代码，我没看懂（我菜，在遍历节点的时候），希望能写几个例子，说明以下里边
`
#filter = {
    isLeafWithoutDeepFilter: () => false,
    isLeafWithDeepFilter: () => false
  }
`  使用场景，还有说明一下代码逻辑啥的，膜拜

**Comment by liuyuanyuannumberone** [comment]
> 大佬你写的应该是网上写的很好的了，希望能继续维护，看了你的源代码，我没看懂（我菜，在遍历节点的时候），希望能写几个例子，说明以下里边 `#filter = { isLeafWithoutDeepFilter: () => false, isLeafWithDeepFilter: () => false }` 使用场景，还有说明一下代码逻辑啥的，膜拜



> 现在正在排查， ![image](https://private-user-images.githubusercontent.com/41810952/394080387-b52c086f-d6c6-4efc-83ec-1a7fc396ce0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3OTgzMDEsIm5iZiI6MTczMzc5ODAwMSwicGF0aCI6Ii80MTgxMDk1Mi8zOTQwODAzODctYjUyYzA4NmYtZDZjNi00ZWZjLTgzZWMtMWE3ZmMzOTZjZTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDAyMzMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OGJkN2QwMzM0MzYyYWEyODQwMmE5NDA3M2I5OThjMjFlYWYxZjJmMjY5NzMzYzBhNDY0NmEwYTI1YmEwZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v-WyAE3voaDLXup4wBI6zBa170JxTeqWjqkFUbuJuvQ) ![image](https://private-user-images.githubusercontent.com/41810952/394080437-465e3693-12b7-4ddc-9c58-2c77c0f6be62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3OTgzMDEsIm5iZiI6MTczMzc5ODAwMSwicGF0aCI6Ii80MTgxMDk1Mi8zOTQwODA0MzctNDY1ZTM2OTMtMTJiNy00ZGRjLTljNTgtMmM3N2MwZjZiZTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDAyMzMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyODgyYjBiOWEzNmNiYTI5OTEzMDMxYTAwNjI3NGFlOGNhMDdjNWVhYWE1YTAxMjI2ZGJhM2QwM2Y3MWQxOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Bg0QHqsBm7wyGbUjHs0N-ZwZnH-PxBwltGRb4WM6X28) 打印出来的canvas 不同电脑大小还是不一样

和电脑本身的显示器配置有关系，放大倍数的问题，但是这样会导致不同电脑pdf效果不一样

**Comment by asdw741111** [comment]
放大倍数会影响高度计算，我修复下
另外那两个filter我会加上详细说明，简单说下场景：
- isLeafWithoutDeepFilter: 叶子节点，整体跨页处理，不再遍历内部元素。可能出现的问题是如果该元素高度超出一页还是会出现截断。优点是不用遍历子元素所以性能好。适用于表格行、图片、canvas等。
- isLeafWithDeepFilter: 叶子节点，整体跨页处理，但是会继续遍历内部元素，确保不会出现高度高于一页的元素被截断问题。缺点是速度会慢，建议用于较高的元素，例如一个大章节。
