### ISSUE TITLE
导出报错，pages未定义

### ISSUE THREAD

**Issue by Jseven86** [asdw741111/jspdf-pro#2]
![image](https://github.com/asdw741111/jspdf-pro/assets/55723225/167f7e1c-f43f-489a-836e-5ed61267471a)
导出时候超长时候就报错了，看了你源码，pages都没定义啊，这你测试过了嘛
![image](https://github.com/asdw741111/jspdf-pro/assets/55723225/f1d5e8dd-c289-4636-be94-b34f1311b72f)

**Comment by asdw741111** [comment]
页眉页脚调整过几次应该这里忘改了，我修复下

**Comment by Jseven86** [comment]
噢噢，请问下你超长处理具体逻辑是啥呀，看了源码一遍还没想通，我这边都解决了其他问题，就是超长浏览器限制这个问题，想学下你的方案

**Comment by asdw741111** [comment]
你这是旧版了，最新版已经解决

**Comment by asdw741111** [comment]
<img width="816" alt="image" src="https://github.com/asdw741111/jspdf-pro/assets/9837532/e767fa64-2f2b-4f8e-9412-37ab64a6143f">

**Comment by asdw741111** [comment]
超长逻辑比较复杂，首先根据宽度计算页面宽度和pdf宽度的比例，结合canvas在浏览器的最大高度获得最大能渲染的html页面高度。
如果小于最大高度就一次渲染并遍历子元素并根据是否跨页等来做细节调整。
如果大于最大高度就需要遍历第一级子元素，执行一遍上边的操作。并且这里由于是遍历子元素所以第一个元素不一定是pdf一页的顶部开始渲染，就需要根据上一步元素渲染完成后剩余空间做调整。

**Comment by Jseven86** [comment]
好的，我研究下，谢谢

**Comment by Jseven86** [comment]
能出篇文章讲下具体解决过程吗哈哈哈哈

**Comment by asdw741111** [comment]
可以考虑，之前我看过一些导出pdf的文章，就是因为他们方案有问题所以才自己写了个，我发现对这个问题解决办法不理解的人还是挺多的，还是有必要写个文章的

**Comment by Jseven86** [comment]
好的大佬，期待你的文章
