### ISSUE TITLE
超长导出，大概25页，一直在导出中，已经10分钟多了还是在导出，这是什么情况，我超长导出就没成功过，还会报注释节点错误

### ISSUE THREAD

**Issue by Jseven86** [asdw741111/jspdf-pro#4]
![image](https://github.com/asdw741111/jspdf-pro/assets/55723225/b6423157-f02d-47f0-8a74-6201726fa2e9)

**Comment by Jseven86** [comment]
知道25页是我自己写的导出方法导出来是25页

**Comment by Jseven86** [comment]
![image](https://github.com/asdw741111/jspdf-pro/assets/55723225/097c7958-c3f2-4650-9db4-26376d195e6c)
这个注释是element组件库的

**Comment by asdw741111** [comment]
为啥会有这么高的注释节点，这部分vue的template代码发一下

**Comment by asdw741111** [comment]
另外如果不需要在页脚显示总页数，不要设置forcePageTotal(true)，这个会导致为了在每一页都能渲染总页数就需要提前先计算一遍，也就是导出时间会加倍。

**Comment by asdw741111** [comment]
特殊情况下确实有问题，已经修复。不对文本、注释、属性节点做异常处理。最新版本0.1.4
