### ISSUE TITLE
非常好的工具，就是ts报错有点多

### ISSUE THREAD

**Issue by flashclub** [asdw741111/jspdf-pro#5]
各种ts报错，例如设置margin和footer：
margin 
设置为 `{ left: 10, top: 20, right: 10, bottom: 20 }` 时报错，需要设置为
`{ unitMode: "html", left: 10, top: 20, right: 10, bottom: 20 }`
footer:
设置为 footer(document.getElementById("footer"), { skipPage: 1 })报错：
> 类型“{ skipPage: number; }”的参数不能赋给类型“{ pageNumSelector: string; pageTotalSelector: string; skipPage: number; }”的参数。
  类型“{ skipPage: number; }”缺少类型“{ pageNumSelector: string; pageTotalSelector: string; skipPage: number; }”中的以下属性: pageNumSelector, pageTotalSelector

**Comment by asdw741111** [comment]
下一版会优化

**Comment by asdw741111** [comment]
已在0.1.5版本优化了ts类型
